<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="pandoc" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <title>throw</title>
  <style type="text/css">
      code{white-space: pre-wrap;}
      span.smallcaps{font-variant: small-caps;}
      span.underline{text-decoration: underline;}
      div.column{display: inline-block; vertical-align: top; width: 50%;}
  </style>
</head>
<body>
<h1 id="throw">throw</h1>
<p>The <code>throw</code> throws a user-defined exception. Execution of the current function will stop (the statements after <code>throw</code> won’t be executed), and control will be passed to the first <a href="try...catch"><code>catch</code></a> block in the call stack. If no <code>catch</code> block exists among caller functions, the program will terminate.</p>
<h2 id="syntax">Syntax</h2>
<pre><code>throw expression;</code></pre>
<p><code>expression</code><br />
The expression to throw.</p>
<h2 id="description">Description</h2>
<p>Use the <code>throw</code> statement to throw an exception. When you throw an exception, <code>expression</code> specifies the value of the exception. Each of the following throws an exception:</p>
<pre><code>throw &#39;Error2&#39;; // generates an exception with a string value
throw 42;       // generates an exception with the value 42
throw true;     // generates an exception with the value true
throw new Error(&#39;Required&#39;);  // generates an error object with the message of Required</code></pre>
<p>Also note that the <code>throw</code> statement is affected by <a href="../lexical_grammar#automatic_semicolon_insertion">automatic semicolon insertion (ASI)</a> as no line terminator between the <code>throw</code> keyword and the expression is allowed.</p>
<h2 id="examples">Examples</h2>
<h3 id="throw-an-object">Throw an object</h3>
<p>You can specify an object when you throw an exception. You can then reference the object’s properties in the <code>catch</code> block. The following example creates an object of type <code>UserException</code> and uses it in a <code>throw</code> statement.</p>
<pre><code>function UserException(message) {
  this.message = message;
  this.name = &#39;UserException&#39;;
}
function getMonthName(mo) {
  mo = mo - 1; // Adjust month number for array index (1 = Jan, 12 = Dec)
  var months = [&#39;Jan&#39;, &#39;Feb&#39;, &#39;Mar&#39;, &#39;Apr&#39;, &#39;May&#39;, &#39;Jun&#39;, &#39;Jul&#39;,
    &#39;Aug&#39;, &#39;Sep&#39;, &#39;Oct&#39;, &#39;Nov&#39;, &#39;Dec&#39;];
  if (months[mo] !== undefined) {
    return months[mo];
  } else {
    throw new UserException(&#39;InvalidMonthNo&#39;);
  }
}

try {
  // statements to try
  var myMonth = 15; // 15 is out of bound to raise the exception
  var monthName = getMonthName(myMonth);
} catch (e) {
  monthName = &#39;unknown&#39;;
  console.error(e.message, e.name); // pass exception object to err handler
}</code></pre>
<h3 id="another-example-of-throwing-an-object">Another example of throwing an object</h3>
<p>The following example tests an input string for a U.S. zip code. If the zip code uses an invalid format, the throw statement throws an exception by creating an object of type <code>ZipCodeFormatException</code>.</p>
<pre><code>/*
 * Creates a ZipCode object.
 *
 * Accepted formats for a zip code are:
 *    12345
 *    12345-6789
 *    123456789
 *    12345 6789
 *
 * If the argument passed to the ZipCode constructor does not
 * conform to one of these patterns, an exception is thrown.
 */

function ZipCode(zip) {
  zip = new String(zip);
  pattern = /[0-9]{5}([- ]?[0-9]{4})?/;
  if (pattern.test(zip)) {
    // zip code value will be the first match in the string
    this.value = zip.match(pattern)[0];
    this.valueOf = function() {
      return this.value
    };
    this.toString = function() {
      return String(this.value)
    };
  } else {
    throw new ZipCodeFormatException(zip);
  }
}

function ZipCodeFormatException(value) {
  this.value = value;
  this.message = &#39;does not conform to the expected format for a zip code&#39;;
  this.toString = function() {
    return this.value + this.message;
  };
}

/*
 * This could be in a script that validates address data
 * for US addresses.
 */

const ZIPCODE_INVALID = -1;
const ZIPCODE_UNKNOWN_ERROR = -2;

function verifyZipCode(z) {
  try {
    z = new ZipCode(z);
  } catch (e) {
    if (e instanceof ZipCodeFormatException) {
      return ZIPCODE_INVALID;
    } else {
      return ZIPCODE_UNKNOWN_ERROR;
    }
  }
  return z;
}

a = verifyZipCode(95060);         // returns 95060
b = verifyZipCode(9560);          // returns -1
c = verifyZipCode(&#39;a&#39;);           // returns -1
d = verifyZipCode(&#39;95060&#39;);       // returns 95060
e = verifyZipCode(&#39;95060 1234&#39;);  // returns 95060 1234</code></pre>
<h3 id="rethrow-an-exception">Rethrow an exception</h3>
<p>You can use <code>throw</code> to rethrow an exception after you catch it. The following example catches an exception with a numeric value and rethrows it if the value is over 50. The rethrown exception propagates up to the enclosing function or to the top level so that the user sees it.</p>
<pre><code>try {
  throw n; // throws an exception with a numeric value
} catch (e) {
  if (e &lt;= 50) {
    // statements to handle exceptions 1-50
  } else {
    // cannot handle this exception, so rethrow
    throw e;
  }
}</code></pre>
<h2 id="specifications">Specifications</h2>
<table>
<thead>
<tr class="header">
<th>
Specification
</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>
<p><a href="https://tc39.es/ecma262/#sec-throw-statement">ECMAScript Language Specification (ECMAScript) <br/></p>
<span class="small">#sec-throw-statement</span></a>
</td>
</tr>
</tbody>
</table>
<h2 id="browser-compatibility">Browser compatibility</h2>
<p>Desktop</p>
<p>Mobile</p>
<p>Chrome</p>
<p>Edge</p>
<p>Firefox</p>
<p>Internet Explorer</p>
<p>Opera</p>
<p>Safari</p>
<p>WebView Android</p>
<p>Chrome Android</p>
<p>Firefox for Android</p>
<p>Opera Android</p>
<p>Safari on IOS</p>
<p>Samsung Internet</p>
<p><code>throw</code></p>
<p>1</p>
<p>12</p>
<p>1</p>
<p>5</p>
<p>4</p>
<p>1</p>
<p>1</p>
<p>18</p>
<p>4</p>
<p>10.1</p>
<p>1</p>
<p>1.0</p>
<h2 id="see-also">See also</h2>
<ul>
<li><a href="try...catch"><code>try...catch</code></a></li>
<li><a href="../global_objects/error"><code>Error</code></a></li>
</ul>
<p>Licensed under the Creative Commons Attribution-ShareAlike License v2.5 or later.<br />
<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw" class="_attribution-link">https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw</a></p>
</body>
</html>
